### PR TITLE
Zoom parameter (android only)

### PR DESCRIPTION
**Pull request by RichardPiel**

### CODE REVIEW

**Comment by RobertSasak** [comment]
NIce work. Can you please also update example?

**Comment by RichardPiel** [comment]
Done, with bug fix about zoom updating.

Sorry my english is not really good.

**Comment by RobertSasak** [comment]
Can you please also update App.js file? https://github.com/RobertSasak/react-native-openalpr/blob/master/example/App.js
Perhaps by adding a button or switch that change zoom. It would be easier to test this new feature.

**Comment by RichardPiel** [comment]
The example application cannot be run at the moment. It crashes at startup while my personal app is running without any problem.


`    --------- beginning of crash
2020-02-24 19:08:01.450 31255-31346/com.rnopenalprexample E/AndroidRuntime: FATAL EXCEPTION: HandlerThread
    Process: com.rnopenalprexample, PID: 31255
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.rnopenalprexample-b7jaTpJY30cdVK99KyaJNg==/base.apk"],nativeLibraryDirectories=[/data/app/com.rnopenalprexample-b7jaTpJY30cdVK99KyaJNg==/lib/arm64, /data/app/com.rnopenalprexample-b7jaTpJY30cdVK99KyaJNg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libopenalpr-native.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.openalpr.AlprJNIWrapper.<clinit>(AlprJNIWrapper.java:9)
        at org.openalpr.OpenALPR$Factory.create(OpenALPR.java:80)
        at com.cardash.openalpr.ALPR.executeRecognition(ALPR.java:119)
        at com.cardash.openalpr.ALPR.access$100(ALPR.java:35)
        at com.cardash.openalpr.ALPR$1.handleMessage(ALPR.java:55)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by RichardPiel** [comment]
Done.

**Comment by RobertSasak** [comment]
I have just tested your PR. Looks good. Well done!
Be aware that we are still missing 64bit library. So you will not be able to publish your app into Google Store.

**Comment by RichardPiel** [comment]
Someone work on 64bit library actually?

**Comment by RobertSasak** [comment]
I have started, but there is more to be done. 
https://github.com/RobertSasak/openalpr-android

**Pull request merged**
